### ISSUE TITLE
Cannot see list of themes

### ISSUE THREAD

**Issue by dgleba** [felladrin/adminer-theme-switcher#1]
In the browser version,  I don't see the list of themes. Can you comment?

![image](https://user-images.githubusercontent.com/4622715/39454893-c6f13bc0-4cab-11e8-9e57-f94315e4cc81.png)

**Comment by felladrin** [comment]
Hi @dgleba,

Thanks for reporting. I was able to reproduce this issue, so I've added one-second delay before displaying the alert in browser. Please, let me know if it works.

**Comment by dgleba** [comment]
Yes, that worked for me. Thanks.
