### ISSUE TITLE
Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by philharmonie** [felladrin/adminer-theme-switcher#2]
### Bug description

```
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/plugins-enabled/AdminerThemeSwitcher.php:129) in /var/www/html/adminer.php on line 1447
```

### Steps to reproduce

1. Add AdminerThemeSwitcher.php to `plugins-enabled`
2. Open adminer in Browser

### Device info

Docker container `adminer:latest`

**Comment by felladrin** [comment]
Hi, @philharmonie.

I'm sorry I didn't clarify in the Readme that _AdminerThemeSwitcher_ was not meant to run as an Adminer Plugin.

It's a standalone PHP script that downloads an `adminer.css` file based on your selected theme.

So there are two ways to run it after placing it in the same folder as `adminer.php`:

1. `php adminer-theme-switcher.php`
2. `php -S localhost:8000` and then access `http://localhost:8000/adminer-theme-switcher.php` on your browser
