### ISSUE TITLE
Preventing "file_get_contents(): SSL operation failed with code 1"

### ISSUE THREAD

**Issue by sohailb108** [felladrin/adminer-theme-switcher#3]
### Is your feature request related to a problem? Please describe.

I'm running it in a docker and when getting the list of themes, the following error raises:

`file_get_contents(): SSL operation failed with code 1`

### Describe the solution you'd like

It is solved by adding SSL options to the "file_get_contents" $context in "getThemeList" function:

        $context = stream_context_create([
            'http' => [
                'method' => 'GET',
                'header' => [
                    'User-Agent: PHP'
                ]
            ],
            'ssl' => [
                "verify_peer" => false,
                "verify_peer_name" => false,
            ]
        ]);

**Comment by felladrin** [comment]
Hi, @sohail-bakhtiari! Thanks for letting me know about this issue and the solution!
Let me add those lines to the code and release a patch.
